name: learndash
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #FIREBASE
  google_sign_in: ^5.4.4
  firebase_core: ^2.5.0
  firebase_messaging: ^14.2.2

  #STORAGE
  hive: ^2.2.3
  path_provider: ^2.0.12
  flutter_downloader: ^1.10.1+2
  external_path: ^1.0.3
  android_path_provider: ^0.3.0
  file: ^6.1.4

  #TOOLS
  screen_protector: ^1.2.0
  extended_image: ^7.0.1
  get: ^4.6.5
  google_fonts: ^4.0.3
  google_mobile_ads: ^2.3.0

  #UTILS
  url_launcher: ^6.1.9
  youtube_player_flutter: ^8.1.2
  intl: ^0.18.0
  share_plus: ^6.3.1
  flutter_phoenix: ^1.1.0

  #WEB
  dio: ^4.0.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  html_unescape: ^2.0.0
  flutter_html: ^2.2.1

  #PAYMENT
  flutter_stripe: ^8.0.0+1
  upi_india: ^3.0.1
  razorpay_flutter: ^1.3.4
  flutter_paypal:
    git:
      url: https://github.com/techgun22/flutter_paypal.git
      ref: main

  #MEDIA PlAYER
  flutter_meedu_videoplayer: ^3.1.2
  chewie_audio: ^1.3.0

  #UI
  cupertino_icons: ^1.0.5
  shimmer: ^2.0.0
  font_awesome_flutter: ^10.4.0
  persistent_bottom_nav_bar: ^5.0.2
  pull_to_refresh: ^2.0.0
  flutter_easyloading: ^3.0.5
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

dependency_overrides:
  flutter_inappwebview:
    git:
      url: https://github.com/rshrc/flutter_inappwebview
      ref: master

flutter:
  uses-material-design: true
  assets:
    - assets/
